# 100 numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.


If you find an error or think you've a better way to solve some of them, feel
free to open an issue at <https://github.com/rougier/numpy-100>.

File automatically generated. See the documentation to update questions/answers/hints programmatically.

Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [17]:
import numpy as np
import torch as t 

#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
print(np.__version__)
print(t.__version__)

1.26.4
2.2.0


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
tenzeros = t.zeros(10)
tenzeros

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [20]:
tenzor = t.randn(4,5,dtype=t.float64)

`.numel` gives the number of elements in a Torch tensor.

**Learning**: Memory size of an array is the amount of computer memory space that the array data structure occupies.

In [21]:
tenzor_memory_size = tenzor.numel() * tenzor.element_size()

Each `float` element in a torch tensor requires 8 bytes, aka the `element_size` of our tensor.

In [23]:
tenzor.element_size()

8

In [24]:
print(f"Memory Size of array/tensor: {tenzor_memory_size} bytes")

Memory Size of array/tensor: 160 bytes


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [25]:
help(t.add)

Help on built-in function add in module torch:

add(...)
    add(input, other, *, alpha=1, out=None) -> Tensor
    
    Adds :attr:`other`, scaled by :attr:`alpha`, to :attr:`input`.
    
    .. math::
        \text{{out}}_i = \text{{input}}_i + \text{{alpha}} \times \text{{other}}_i
    
    
    Supports :ref:`broadcasting to a common shape <broadcasting-semantics>`,
    :ref:`type promotion <type-promotion-doc>`, and integer, float, and complex inputs.
    
    Args:
        input (Tensor): the input tensor.
        other (Tensor or Number): the tensor or number to add to :attr:`input`.
    
    Keyword arguments:
        alpha (Number): the multiplier for :attr:`other`.
        out (Tensor, optional): the output tensor.
    
    Examples::
    
        >>> a = torch.randn(4)
        >>> a
        tensor([ 0.0202,  1.0985,  1.3506, -0.6056])
        >>> torch.add(a, 20)
        tensor([ 20.0202,  21.0985,  21.3506,  19.3944])
    
        >>> b = torch.randn(4)
        >>> b
       

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

**Learning**: The null vector is defined to have zero magnitude and no particular direction

In [26]:
tenull = t.zeros(10)
tenull[4] = 1
tenull

tensor([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [27]:
fiftylist = []
for i in range(10,50,1):
    fiftylist.append(i)

tenzor_fifty = t.tensor(fiftylist)
    

In [28]:
tenzor_fifty

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

**Lesson**: Better, actual way to do it is to use `torch.arange`

In [29]:
tenzor_fifty = t.arange(10,50)
tenzor_fifty

tensor([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
        28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45,
        46, 47, 48, 49])

#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [32]:
tenzor_fifty_reversed = tenzor_fifty.__reversed__()

In [34]:
tenzor_fifty_reversed

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10])

In [35]:
tenzor_fifty[::-1]

ValueError: step must be greater than zero

**Learning**: The torch method `flip(input,dims)` can be used to reverse a tensor along specific dims

In [42]:
tenzor_fifty.flip(dims=[0])

tensor([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32,
        31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14,
        13, 12, 11, 10])

#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [45]:
t.arange(0,9).reshape(3,3)

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [46]:
tenzor = t.tensor([1,2,0,0,4,0])

In [47]:
indices = []
for index,value in enumerate(tenzor):
    if value!=0:
        indices.append(index)

indices

[0, 1, 4]

**Learning**: Apparently, there's a torch built-in method for it. Its called `torch.nonzero`

In [48]:
t.nonzero(tenzor)

tensor([[0],
        [1],
        [4]])

#### 11. Create a 3x3 identity matrix (★☆☆)

In [50]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

**Learning**: In numpy, you can use `identity` method. In Torch, the method is called `eye`

In [51]:
t.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

#### 12. Create a 3x3x3 array with random values (★☆☆)

In [52]:
t.rand(3,3,3)

tensor([[[5.1860e-01, 2.4624e-01, 7.6888e-01],
         [9.5515e-01, 4.1350e-01, 8.8875e-01],
         [3.6553e-01, 6.6275e-01, 4.3328e-01]],

        [[2.6166e-01, 1.8687e-02, 7.0143e-04],
         [4.6024e-01, 7.1645e-02, 4.4938e-01],
         [4.1472e-01, 7.7098e-01, 3.3727e-01]],

        [[9.6811e-01, 2.6897e-01, 9.9964e-01],
         [5.6995e-01, 3.5587e-01, 9.6377e-01],
         [9.5560e-01, 6.2336e-01, 4.1491e-02]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [53]:
tenbyten = t.rand(10,10)

In [56]:
tenbyten.min(),tenbyten.max()

(tensor(9.9540e-05), tensor(0.9911))

#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [57]:
thirty = t.rand(30)

In [63]:
t.mean(thirty)

tensor(0.5211)

#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [67]:
import torch

In [68]:
onezero = torch.ones(3,3)
onezero[1,1] = 0
onezero

tensor([[1., 1., 1.],
        [1., 0., 1.],
        [1., 1., 1.]])

In [69]:
onezero = torch.ones(7,7)
onezero[1:-1,1:-1] = 0
onezero

tensor([[1., 1., 1., 1., 1., 1., 1.],
        [1., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 1.],
        [1., 0., 0., 0., 0., 0., 1.],
        [1., 1., 1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [73]:
len(onezero.shape)

2

In [77]:
torch.zeros(3,3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [86]:
zeros_shape = {}
for i in range(len(onezero.shape)):
    zeros_shape[i] = onezero.shape[i] + 2

zeross = torch.zeros(list(zeros_shape.values()))
zeross[1:-1,1:-1] = onezero
zeross


tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 0., 0., 0., 0., 0., 1., 0.],
        [0., 1., 1., 1., 1., 1., 1., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

**Learning**: There's a straightforward way to add padding. It is `torch.nn.functional.pad(input,pad,mode,value)` where 

- pad is a tuple (left,right,top,bottom) and each element here is how much padding you want to add on each corner.
- Value specifies the value you want to add.
- Mode has different categories, with `constant` being the default value.

In [96]:
torch.nn.functional.pad(onezero,(1,1,1,1),'constant',2)

tensor([[2., 2., 2., 2., 2., 2., 2., 2., 2.],
        [2., 1., 1., 1., 1., 1., 1., 1., 2.],
        [2., 1., 0., 0., 0., 0., 0., 1., 2.],
        [2., 1., 0., 0., 0., 0., 0., 1., 2.],
        [2., 1., 0., 0., 0., 0., 0., 1., 2.],
        [2., 1., 0., 0., 0., 0., 0., 1., 2.],
        [2., 1., 0., 0., 0., 0., 0., 1., 2.],
        [2., 1., 1., 1., 1., 1., 1., 1., 2.],
        [2., 2., 2., 2., 2., 2., 2., 2., 2.]])

#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

Result:

```python
0 * np.nan # nan
np.nan == np.nan #False
np.inf > np.nan #False
np.nan - np.nan #nan
np.nan in set([np.nan]) #True
0.3 == 3 * 0.1 #False
```

**Learning**: 
- nan cannot be logically compared to any number
- nan cannot be equal to any number, including itself
- Any arithmetic operation with nan results in nan
- 3*0.1 is not equal to 0.3, but is actually equal to 0.3 with a rounding error (aka followed by many decimal places).

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

#### 22. Normalize a 5x5 random matrix (★☆☆)

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

#### 29. How to round away from zero a float array ? (★☆☆)

#### 30. How to find common values between two arrays? (★☆☆)

#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

#### 32. Is the following expressions true? (★☆☆)
```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

#### 40. Create a random vector of size 10 and sort it (★★☆)

#### 41. How to sum a small array faster than np.sum? (★★☆)

#### 42. Consider two random array A and B, check if they are equal (★★☆)

#### 43. Make an array immutable (read-only) (★★☆)

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

#### 46. Create a structured array with `x` and `y` coordinates covering the [0,1]x[0,1] area (★★☆)

#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)

#### 49. How to print all the values of an array? (★★☆)

#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

#### 54. How to read the following file? (★★☆)
```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

#### 56. Generate a generic 2D Gaussian-like array (★★☆)

#### 57. How to randomly place p elements in a 2D array? (★★☆)

#### 58. Subtract the mean of each row of a matrix (★★☆)

#### 59. How to sort an array by the nth column? (★★☆)

#### 60. How to tell if a given 2D array has null columns? (★★☆)

#### 61. Find the nearest value from a given value in an array (★★☆)

#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

#### 63. Create an array class that has a name attribute (★★☆)

#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

#### 69. How to get the diagonal of a dot product? (★★★)

#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

#### 72. How to swap two rows of an array? (★★★)

#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

#### 74. Given a sorted array C that corresponds to a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

#### 75. How to compute averages using a sliding window over an array? (★★★)

#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z[0],Z[1],Z[2]) and each subsequent row is  shifted by 1 (last row should be (Z[-3],Z[-2],Z[-1]) (★★★)

#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i (P0[i],P1[i])? (★★★)

#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P[j]) to each line i (P0[i],P1[i])? (★★★)

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

#### 82. Compute a matrix rank (★★★)

#### 83. How to find the most frequent value in an array?

#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

#### 85. Create a 2D array subclass such that Z[i,j] == Z[j,i] (★★★)

#### 86. Consider a set of p matrices with shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)

#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

#### 88. How to implement the Game of Life using numpy arrays? (★★★)

#### 89. How to get the n largest values of an array (★★★)

#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)

#### 91. How to create a record array from a regular array? (★★★)

#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

#### 95. Convert a vector of ints into a matrix binary representation (★★★)

#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)